openapi: 3.1.0
info:
  title: LLM PIC API Specification
  version: 0.1.0
servers:
  - url: http://localhost/api/v1
tags:
  - name: LLM
  - name: User
  - name: Session

paths:
  /tutorResponse:
    post:
      tags:
        - LLM
      operationId: tutorRespond
      description: Acquire a streaming response from LLM background.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LLMPropmt'
      responses:
        '200':
          description: Successful
          content:
            text/plain:
              schema:
                type: string
                format: binary
                maxLength: 2048
        '400':
          description: Failed
        '429':
          description: Rate-limited


  /session:
    post:
      tags:
          - Session
      security: []
      operationId: sessionLogin
      description: Authenticate and create a new session.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful, returning a new access token assigned to the session.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  token:
                    type: string
        '400':
          description: Failed
    delete:
      tags:
        - Session
      operationId: sessionLogout
      description: Logout and destroy the session.
      responses:
        '200':
          description: Successful

  /user:
    post:
      tags:
        - User
      security: []
      operationId: userCreate
      description: Create a new user.
      requestBody:
        description: Requested user.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful
        '400':
          description: Failed
        '429':
          description: Rate-limited

  /courses:
    get:
      tags:
        - Courses
      security: []
      operationId: enumerateCourses
      description: Get all available courses.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 0
        email:
          type: string
          example: "example@example"
        userName:
          type: string
          example: "User"
        password:
          type: string
          format: password
        status:
          type: integer
    LLMPropmt:
      type: object
      properties:
        code:
          type: string
        prompt:
          type: string
    Class:
      type: object
      properties:
        id:
          type: string
    Course:
      type: object
      properties:
        id:
          type: string
          description: 'An identifier of the course. Note that it is also used to access the course.'
        description:
          type: string
          description: 'Description'
        classes:
          type: array
          items:
            $ref: '#/components/schemas/Class'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: token

security:
  - ApiKeyAuth: []
